---
title: 'Coding Challenge 5: Data Wrangling'
author: "Mamata K C"
date: "2025-03-20"
output: md_document:
  variant: gfm
pdf_document
toc: TRUE
---

Data wrangling – 25 pts

PLEASE READ THIS BEFORE CONTINUING

This assignment will help you practice integrating some of the tidyverse functions into your R scripts. It will also involve some more practice with GitHub. You may collaborate with a partner to enhance your learning experience. Please ensure the following:

•	Collaboration: If you work with a partner, include both names on the final submission by editing the YAML header.
•	Submission: Only one person should submit the assignment to Canvas in a Word document or .pdf file generated through R markdown. Additionally, you should provide a link to your GitHub, where the assignment should be viewable by rendering it as a GitHub-flavored markdown file. 
•	Setup: It is also assumed you already have a GitHub repository for this class. 
•	Time: This should take you no longer than the class period to complete. 


1.	3 pts. Download two .csv files from Canvas called DiversityData.csv and Metadata.csv, and read them into R using relative file paths.
2.	4 pts. Join the two dataframes together by the common column ‘Code’. Name the resulting dataframe alpha.
3.	4 pts. Calculate Pielou’s evenness index: Pielou’s evenness is an ecological parameter calculated by the Shannon diversity index (column Shannon) divided by the log of the richness column. 
a.	Using mutate, create a new column to calculate Pielou’s evenness index. 
b.	Name the resulting dataframe alpha_even.
4.	4. Pts. Using tidyverse language of functions and the pipe, use the summarise function and tell me the mean and standard error evenness grouped by crop over time.
a.	Start with the alpha_even dataframe
b.	Group the data: group the data by Crop and Time_Point.
c.	Summarize the data: Calculate the mean, count, standard deviation, and standard error for the even variable within each group.
d.	Name the resulting dataframe alpha_average
5.	4. Pts. Calculate the difference between the soybean column, the soil column, and the difference between the cotton column and the soil column
a.	Start with the alpha_average dataframe
b.	Select relevant columns: select the columns Time_Point, Crop, and mean.even.
c.	Reshape the data: Use the pivot_wider function to transform the data from long to wide format, creating new columns for each Crop with values from mean.even.
d.	Calculate differences: Create new columns named diff.cotton.even and diff.soybean.even by calculating the difference between Soil and Cotton, and Soil and Soybean, respectively.
e.	Name the resulting dataframe alpha_average2
6.	4 pts. Connecting it to plots
a.	Start with the alpha_average2 dataframe
b.	Select relevant columns: select the columns Time_Point, diff.cotton.even, and diff.soybean.even.
c.	Reshape the data: Use the pivot_longer function to transform the data from wide to long format, creating a new column named diff that contains the values from diff.cotton.even and diff.soybean.even.
i.	This might be challenging, so I’ll give you a break. The code is below.

pivot_longer(c(diff.cotton.even, diff.soybean.even), names_to = "diff")

d.	Create the plot: Use ggplot and geom_line() with ‘Time_Point’ on the x-axis, the column ‘values’ on the y-axis, and different colors for each ‘diff’ category. The column named ‘values’ come from the pivot_longer. The resulting plot should look like the one to the right. 

7.	2 pts. Commit and push a gfm .md file to GitHub inside a directory called Coding Challenge 5. Provide me a link to your github written as a clickable link in your .pdf or .docx

